import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import DataContextProvider from '@/context/DataContext'
import SearchContextProvider from '@/context/SearchContext'
import UserContextProvider from '@/context/UserContext'
import ToastComponent from '@/components/ToastComponent'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SearchContextProvider>
          <UserContextProvider>
            <DataContextProvider>
              <ToastComponent />
              <Header />
              {children}
            </DataContextProvider>
            <Footer />
          </UserContextProvider>
        </SearchContextProvider>
      </body>
    </html>
  )
}
